apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: demo
  namespace: demo
spec:
  host: demo.demo.svc.cluster.local
  subsets:
  - name: canary   # referenced in canary.trafficRouting.istio.destinationRule.canarySubsetName
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
  - name: stable   # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN

