apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: demo
  namespace: demo
spec:
  host: demo.demo.svc.cluster.local
  subsets:
  - name: canary   # referenced in canary.trafficRouting.istio.destinationRule.canarySubsetName
    labels:
      app: canary
  - name: stable   # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
    labels:
      app: stable
