apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo
  namespace: demo
spec:
  replicas: 5
  strategy:
    canary:
      steps:
        - setWeight: 30
        - pause: {}  # pause indefinitely
        # - setWeight: 40
        # - pause: {}
        # - setWeight: 60
        # - pause: {duration: 10}
        # - setWeight: 80
        # - pause: {duration: }
      trafficRouting:
        istio:
          virtualService:
            name: demo        # required
            # routes:
            #   - primary
          destinationRule:
            name: demo   # required
            canarySubsetName: canary  # required
            stableSubsetName: stable  # required

  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: sonnguyen129/nginx-web:0.0.3
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
        livenessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: "/"
            port: 80
